let antNames = [
  "Ant-onio Banderas",
  "Picante the Picnic Pilferer",
  "Sir Lancelot the Lance-ant",
  "Ant-thony Humperdink",
  "Queen Eliza-ant",
  "Sir Digglesworth",
  "Ant-elope Cruz",
  "Munchkin the Ant-eater",
  "Ant-ony Stark, the Iron Worker",
  "Count Dracul-ant",
  "Ant-sy Pantsy",
  "Sir Tunnels-a-Lot",
  "Captain Cruncher the Ant-obese",
  "Ant-ique Collector",
  "Lebron James, the Slam Dunker Ant",
  "Ant-astasia, the Ballerina",
  "Ant-ony the Comed-ant",
  "Ant-thony and Cleop-ant-ra",
  "Colonel Must-ant",
  "Ant-thropologie Explorer",
]

let spiderNames = [
  "Venomstrike the Arachnid Overlord",
  "Grim Fangs the Shadow Stalker",
  "Black Widowmaker",
  "Draculweaver, the Bloodsucker",
  "Scarabula, the Scarab Spinner",
  "Arachnus the Sinister Silk spinner",
  "Deathspinner the Eight Legged Reaper",
  "Arachno Bane the Web Weaver of Doom",
  "Skullduggery the Silent Stalker",
  "Vortex the Dark Widow",
  "Dreadfang the Creeping Terror",
  "Tarantula Khan, the Emperor of Fear",
  "Widow's Wrath the Ensnaring Menace",
  "Arach no Mercy",
  "Count Vile arach, the Nosferatu",
  "Abyssal Arachnid the Weaver of Despair",
  "Fangoria the Arachnid Assassin",
  "Malevolence the Silent Specter",
  "Nycto Nightmare the Eight Legged Horror",
  "Ravagearach, the Devourer of Hope",
]

let soldierNames = [
  "Sergeant Stinger, the Battle - hardened Ant",
  "Colonel Carapace, the Iron Mandible",
  "Major Mandible Crusher",
  "Captain Cutters, the Razorblade Commander",
  "General Grizzle - jaws",
  "Commandant Crushinator",
  "Corporal Clawhammer",
  "Lieutenant Lethal Legs",
  "Major Marauder, the Ambush Maestro",
  "Sargeant Scorcher, the Flamethrower Ant",
  "Bullet Ant Billy, the Sniper Specialist",
  "Tank - top the Tank Commander",
  "Commander Chitin - Chisel",
  "Private Pincer Fury",
  "Elite Exo - soldier X - 1",
  "First Lieutenant Thorax Thunder",
  "Sentinel Scorpion, the Battle Vanguard",
  "Sergeant Slasher, the Machete Mauler",
  "Alpha Assault Ant",
  "Master Sergeant Mortar Maul",
]
